spring:
  application:
    name: com.joshgav.apiserver.Application
  flyway.enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  datasource:
    initialization-mode: always
    username: apiserver
    password: apiserver
    url: jdbc:postgresql://localhost:5432/apiserverdb
    # url: jdbc:postgresql://localhost:5432/postgres
  sleuth:
    enabled: true

server:
  servlet:
    port: 8080

management:
  server.port: 9090
  health.defaults: enabled
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always
      show-components: always
    info.enabled: true
  endpoints.web.exposure.include: "info,health,configprops,env,metrics,prometheus"

springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true
  packagesToScan: com.joshgav.apiserver.controller

keycloak:
  auth-server-url: http://keycloak-insecure-app.apps.aws-ipi.sandbox930.opentlc.com/auth/
  realm: app
  resource: spring-apiserver
  ssl-required: none
  principal-attribute: preferred_username
  credentials:
    secret: TBD
# security-constraints:
# - authRoles:
#   - spring
#   - user
#   securityCollections:
#   - patterns:
#     - '/*'
